#!/usr/bin/env python3
"""Generate original synthetic media and exercise the actual FFmpeg pipeline.
All pass statuses here are fixture state for software tests, NOT artistic signoff.
"""
from pathlib import Path
import argparse
import importlib.util
import json
import math
import wave
import struct

ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('mad',ROOT/'scripts/mad.py')
mad=importlib.util.module_from_spec(spec);spec.loader.exec_module(mad)

def main():
    p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);p.add_argument('--fps',default='24')
    p.add_argument('--delivery',action='store_true');a=p.parse_args()
    d=a.out.resolve();d.mkdir(parents=True,exist_ok=True)
    video=d/'synthetic source.mp4';image=d/'synthetic still.png';audio=d/'synthetic music.wav'
    mad.ff(['-f','lavfi','-i','testsrc2=size=1920x1080:rate=24:duration=8',
            '-c:v','libx264','-threads','2','-preset','ultrafast','-crf','24','-pix_fmt','yuv420p',
            '-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-color_range','tv',str(video)])
    mad.ff(['-f','lavfi','-i','testsrc2=size=2560x1440:rate=1','-frames:v','1',str(image)])
    sr=48000
    # A quiet tone bed and 120 BPM transient clicks; no copyrighted music.
    with wave.open(str(audio),'wb') as f:
        f.setnchannels(2);f.setsampwidth(2);f.setframerate(sr)
        data=bytearray()
        for i in range(sr*8):
            t=i/sr;phase=t%0.5
            sample=.055*math.sin(2*math.pi*220*t)+(.1*math.sin(2*math.pi*1200*t)*math.exp(-phase*150) if phase<.04 else 0)
            v=round(sample*32767);data+=struct.pack('<hh',v,v)
        f.writeframes(data)
    review={'native_quality':'pass','no_burned_subtitles':'pass','no_logos':'pass','color_interpretation':'pass',
            'evidence':'Original synthetic software-test fixture; not a human review of an AMV',
            'clean_ranges':[['0','8']]}
    t=mad.read_json(ROOT/'templates/timeline.json');t['name']='SYNTHETIC PIPELINE TEST — NOT AN AMV';t['fps']=a.fps
    for aid,kind,path in [('v','video',video),('i','image',image),('a','audio',audio)]:
        t['assets'].append({'id':aid,'kind':kind,'path':path.name,'provenance':'Generated by tests/smoke.py',
                            'usage_basis':'Original synthetic software test','review':review})
    # At 24 fps: cut -> dissolve -> cut; retime and still camera are covered.
    t['shots']=[
        {'id':'S1','asset_id':'v','source_in':'0','speed':'1','start_frame':0,'duration_frames':36,
         'transition_in':{'type':'cut','duration_frames':0},'narrative_function':'synthetic cut test','sync_anchor':'frame 0'},
        {'id':'S2','asset_id':'v','source_in':'2','speed':'3/2','start_frame':36,'duration_frames':48,
         'transition_in':{'type':'cut','duration_frames':0},'narrative_function':'synthetic retime test','sync_anchor':'frame 36'},
        {'id':'S3','asset_id':'v','source_in':'5','speed':'1','start_frame':72,'duration_frames':36,
         'transition_in':{'type':'dissolve','duration_frames':12},'narrative_function':'synthetic dissolve test','sync_anchor':'frame 72'},
        {'id':'S4','asset_id':'i','source_in':'0','speed':'1','start_frame':108,'duration_frames':36,
         'transition_in':{'type':'cut','duration_frames':0},'narrative_function':'synthetic still camera test','sync_anchor':'frame 108',
         'motion':{'zoom_start':1,'zoom_end':1.1,'x_start':.4,'x_end':.6,'y_start':.5,'y_end':.5}}]
    t['duration_frames']=144
    t['audio']=[{'asset_id':'a','source_in':'0','start_frame':0,'duration_frames':144,'gain_db':0,
                  'fade_in_frames':2,'fade_out_frames':12},
                {'asset_id':'a','source_in':'0','start_frame':72,'duration_frames':12,'gain_db':-18,
                  'fade_in_frames':1,'fade_out_frames':3}]
    t['reviews']={k:'pass' for k in t['reviews']} # Test fixture, never use to approve real work.
    captions=(ROOT/'templates/captions.ass').read_text()+'Dialogue: 0,0:00:00.20,0:00:02.00,Default,,0,0,0,,SYNTHETIC TEST - NOT AN AMV\n'
    (d/'captions.ass').write_text(captions);t['caption_file']='captions.ass'
    mad.write_json(d/'timeline.json',t)
    validation=mad.validate_data(t,d,final=a.delivery)
    if not validation['ok']:raise RuntimeError(validation)
    result=mad.render(d/'timeline.json',d/'smoke.mp4',draft=not a.delivery,normalize=True,overwrite=True)
    mad.cutlist(d/'timeline.json',d/'cutlist.csv')
    quality=mad.qa(d/'smoke.mp4',d/'timeline.json',d/'qa.json',True)
    if quality['errors']:raise RuntimeError(quality)
    mad.scenes(d/'smoke.mp4',d/'scene-candidates.csv',.2)
    mad.contact(d/'smoke.mp4',d/'contact',2,4)
    mad.write_json(d/'result.json',{'passed':True,'test_type':'synthetic integration, not AMV artistic evaluation',
                                 'fps':a.fps,'profile':'delivery' if a.delivery else 'draft',
                                 'decoded_frames':144,'validation':validation,'render_status':result['status'],
                                 'automated_qa':quality['automated_status']})
    print(json.dumps(mad.read_json(d/'result.json'),ensure_ascii=False,indent=2))

if __name__=='__main__':main()
